spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:testdbI
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers:
      - localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: 1
      properties:
        spring.json.add.type.headers: true

    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        properties:
        spring.json.trusted.packages: "com.krishna9787.inventory_service.dto"
        spring.json.type.mapping: "com.krishna9787.order_service.dto.OrdersDto:com.krishna9787.inventory_service.dto.OrderCreatedEventDto"

server:
  port: 8082
